In [1]:
import glob
import pandas as pd

In [17]:
files_df=pd.DataFrame(glob.glob("/mount/studenten/DH_Master/compounding/google/tempo*"))
files_df=files_df[0].str.split('_',expand=True)

In [18]:
files_df

8
na.csv     96
med.csv    96
Name: count, dtype: int64

In [19]:
files_df.groupby([6,7]).size()

6    7
10   0       8
     10      8
     100     8
     1000    8
     50      8
     500     8
100  0       8
     10      8
     100     8
     1000    8
     50      8
     500     8
20   0       8
     10      8
     100     8
     1000    8
     50      8
     500     8
50   0       8
     10      8
     100     8
     1000    8
     50      8
     500     8
dtype: int64

In [55]:
files_df[[3,4,5,6]].value_counts().to_frame().reset_index().pivot_table(index=[3,4,5],columns=6,values='count')

6                      0   10  100  1000   50  500
3    4        5
PPMI Tagged   10     4.0  4.0  4.0   4.0  4.0  4.0
              100    4.0  4.0  4.0   4.0  4.0  4.0
              10000  4.0  4.0  4.0   4.0  4.0  4.0
              20     4.0  4.0  4.0   4.0  4.0  4.0
              50     4.0  4.0  4.0   4.0  4.0  4.0
     UnTagged 10     4.0  4.0  4.0   4.0  4.0  4.0
              100    4.0  4.0  4.0   4.0  4.0  4.0
              10000  4.0  4.0  4.0   4.0  4.0  4.0
              20     4.0  4.0  4.0   4.0  4.0  4.0
              50     4.0  4.0  4.0   4.0  4.0  4.0
RAW  Tagged   10     4.0  4.0  4.0   4.0  4.0  4.0
              100    4.0  4.0  4.0   4.0  4.0  4.0
              10000  4.0  4.0  4.0   4.0  4.0  4.0
              20     4.0  4.0  4.0   4.0  4.0  4.0
              50     4.0  4.0  4.0   4.0  4.0  4.0
     UnTagged 10     4.0  4.0  4.0   4.0  4.0  4.0
              100    4.0  4.0  4.0   4.0  4.0  4.0
              10000  4.0  4.0  4.0   4.0  4.0  4.0
              20     4.0  4.0  4.0   4.0  4.0  4.0
              50     4.0  4.0  4.0   4.0  4.0  4.0

In [14]:
files_df.loc[files_df[5]=="10"]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8]
Index: []

In [5]:
files_df.loc[files_df[3]=="RAW"].groupby([5,6]).size()

5      6
10     0       4
       10      4
       100     8
       1000    8
       50      8
       500     4
100    0       8
       10      8
       100     8
       1000    8
       50      8
       500     8
10000  0       8
       10      8
       100     8
       1000    8
       50      8
       500     8
20     0       8
       10      8
       100     8
       1000    8
       50      8
       500     8
50     0       8
       10      8
       100     8
       1000    8
       50      8
       500     8
dtype: int64

ppmi, 100,         *0*,
        20,        
        50,

In [7]:
files_df.groupby([3,4]).size()

3     4
PPMI  Tagged       84
      UnTagged    120
RAW   Tagged      108
      UnTagged    120
dtype: int64

In [ ]:
PPMI,20, 0,